### ISSUE TITLE
Plans for optional records support

### ISSUE THREAD

**Issue by youngkidwarrior** [glennsl/rescript-json-combinators#1]
Rescript v10 has implemented support for optional record fields
https://github.com/rescript-lang/rescript-compiler/issues/5654

Any plans on implementing this instead of using Option?

Is it even feasible with the API. I might take a look at it myself if you think it is possible

**Comment by glennsl** [comment]
Hi. I'm not aware of any syntax for conditionally setting an `@optional` field individually (the issue you reference seems to just be about a printing bug), but if there is I don't see why it wouldn't work with the existing API. Whether it uses `option`s directly, or branching on an `option`. I don't know how else it would work.

**Comment by glennsl** [comment]
I'm assuming this has been answered adequately. But feel free to re-open if necessary.

**Comment by hellos3b** [comment]
I'm facing this as well, when using the optional `?` syntax, the `field.optional` doesn't resolve right

![Screenshot 2023-01-03 at 9 44 49 AM](https://user-images.githubusercontent.com/4062679/210412152-f115b6d3-3710-4276-a11f-2109df7c8ed4.png)

```res
type foo = {
  a: string,
  b?: string,
}

let decoder = {
  open Json.Decode
  object(field => {
    a: field.required(. "a", string),
    b: field.optional(. "b", string),
  })
}
```

I think it would make more sense if `field.optional<'a>` returns `'a` instead of `option<'a>`, and then use the `Decode.option(string)` for the explicit option type

```res
let decoder = object(field => {
  a: field.required(. "a", option(string)),
  b: field.optional(. "b", string)
}
```

**Comment by glennsl** [comment]
> I'm facing this as well, when using the optional ? syntax, the field.optional doesn't resolve right

According to the documentation, if you want to assign an option to an optional field, you need to prefix it with `?`:

```rescript
type foo = {
  a: string,
  b?: string,
}

let decoder = {
  open Json.Decode
  object(field => {
    a: field.required(. "a", string),
    b: ?field.optional(. "b", string),
  })
}
```

> I think it would make more sense if field.optional<'a> returns 'a instead of option<'a>, and then use the Decode.option(string) for the explicit option type

Then it wouldn't be optional... You can get this behavior by using `field.required` instead, <s>but the implication of using ´option´ is that you're not able to distinguish between the field not being present and the the type being wrong.</s> *Edit: Strike that, this is how it used to work with `bs-json`, which was closer to Elm's decoders. `option` now only returns `None` if it's `null`, not if the inner decoder fails, and not if it's `undefined` either, since `undefined` is not a JSON value*

**Comment by hellos3b** [comment]
> `b: ?field.optional(. "b", string),`

Ah man thanks, this is the syntax I didn't know existed! My suggestion was based off trying to get the types to agree on my own fork, you can disregard it :)
